Project config upgrades

diff --git a/scripts/git/pre-commit b/scripts/git/pre-commit
--- a/scripts/git/pre-commit
+++ b/scripts/git/pre-commit
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-CHANGED_KT_FILES=$(git diff --cached --name-only --diff-filter=ACM "./**/*.kt" "./**/*.kts")
+CHANGED_KT_FILES=$(git diff --cached --name-only --diff-filter=ACMR "./**/*.kt" "./**/*.kts")
 if [ ! -z "$CHANGED_KT_FILES" ]; then
     # auto-format
     ./gradlew ktlintFormat -PKTLINT_INCLUDES="$CHANGED_KT_FILES"
@@ -8,4 +8,10 @@ if [ ! -z "$CHANGED_KT_FILES" ]; then
 
     # save changes back to git commit
     git add $(echo "$CHANGED_KT_FILES" | paste -s -d " " -)
+
+    CHANGED_KT_FILES=$(git diff --cached --name-only)
+    if [ -z "$CHANGED_KT_FILES" ]; then
+        echo -e "\n\nAborting commit. All changes were restored by ktlint\n\n"
+        exit 1
+    fi
 fi
